### ISSUE TITLE
Unable to update Radarr

### ISSUE THREAD

**Issue by Landelor** [recyclarr/recyclarr#106]
Hi,

Not sure what I did wrong.
I changed from 'names' to 'trash_ids' as suggested in the log.
After running cron.sh I get this:

`[WRN] The Custom Formats below do not exist in the guide and will be skipped`

and it removed all the CFs from Radarr.
At the moment it doesn't work for names or trash_ids.
I reverted to an old backup and still no go.

Any help is appreciated.

Regards,
Landelor

**Comment by rcdailey** [comment]
What version are you running?

**Comment by rcdailey** [comment]
Probably a dupe of #107
