### ISSUE TITLE
Add configurable notifications to recyclarr

### ISSUE THREAD

**Issue by hvalev** [recyclarr/recyclarr#114]
Something like https://github.com/caronc/apprise could be embedded in the docker image to allow notifications to be sent to arbitrary endpoints when services are updated. Could be configured through the .yaml configuration file.

**Comment by rcdailey** [comment]
I plan to address this soon. Is apprise the most recommended solution here?

**Comment by hvalev** [comment]
There are a few other packages that do the same thing, but apprise is actively maintained, updated and developed. However, apprise is a python package, so it might be difficult to use it as-is. However, there is the apprise server, which encapsulates the functionality and allows you to send notification to rest endpoint. Check https://github.com/caronc/apprise-api. It should be fairly straightforward to provide the option of using recyclarr + apprise with docker through a docker-compose file and allow configuring recyclarr through environment variables to configure the communication to the apprise server rest api.

**Comment by rcdailey** [comment]
Yeah I don't see a .NET API. I can use Flurl to invoke the REST API though. I'll definitely give this a closer look when I have time to get around to it. Thanks for the information @hvalev.

**Comment by hvalev** [comment]
Hey @rcdailey, I stumbled upon the [ntfy](https://ntfy.sh/) library. There is also a .NET variant [here](https://github.com/nwithan8/ntfy-dotnet) which should work with [apprise](https://github.com/caronc/apprise/wiki/Notify_ntfy)

**Comment by rcdailey** [comment]
That is excellent. Thank you @hvalev!

**Comment by rcdailey** [comment]
I'm starting on this today. I should have asked the obvious question earlier, but can you folks share with me what kind of notifications you feel would be interesting? Obviously, a notification when sync completes and the status (completed or failed) is a good starting point. But, beyond that:

- Should there be 1 notification *per instance* or *per `sync` command*?
- What level of detail should be published?
- Can people give me examples of how they'd use these notifications (this will illuminate some requirements).

**Comment by hvalev** [comment]
Hi @rcdailey , sorry for jumping in late.

I think that the notifications should be split per service (radarr/sonarr instance), but collated for all updates made on a service. The level of detail should be configurable. Low-level of detail would be *what* (as in which parameter) was updated and high-level of detail would be *what value was updated with a from and to*. The notifications, at least in my case, would mostly serve to check that the recyclarr service is alive and to potentially catch erroneously updated values (e.g. file sizes). At the moment, the if, when and what was changed is obscured with no notice or confirmation. The only way to truly check is if one is inspecting the logs or manually writing down all values and coming back the next day to compare. Ideally the notifications should also include failures to reach any of the configured services. I hope this helps.

**Comment by rcdailey** [comment]
> the notifications should be split per service (radarr/sonarr instance), but collated for all updates made on a service

Can you explain this some more? I'm not sure what you mean by this. What would this look like in terms of Apprise? Are you suggesting that if, for example, you set up Apprise to forward notifications to Discord, that you expect 1 discord message in your channel for every service? So if you had 5 instances you synced. Running `recyclarr sync` results in *at least* 5 separate discord messages?

**Comment by hvalev** [comment]
Exactly, for each configured instance there would be a single notification which includes all changes made to the quality and/or release profiles, file size preferences, etc... If I'm not mistaken, the apprise api accepts simple POST requests, where the body is the notification text. The notification text could be rendered in markdown (similar to how radarr or sonarr send notifications for episodes or movies). In this line of thought, it could be useful to come up with a sensible markdown template which can be 'populated' with changes made. But the latter part is just nice to have.

**Comment by rcdailey** [comment]
Here is what I have in mind so far as far as `settings.yml` goes:

```yml
notifications:
  apprise:
    base_url: http://localhost:8000
    key: apprise
    tags: foo bar, baz
```

Some notes:

- `notifications` is meant to be extensible. If another notification service besides Apprise is added in the future, the structure here allows for that.
- `base_url` would be what you bookmark to hit the Apprise web UI
- `key` is a configuration key in Apprise that you use to associate notification services to Recyclarr
- `tags` is an optional field for tags support.

So far I believe this covers enough for a MVF. I'm open to any feedback. If I hear nothing in response, I'll just assume no one has a problem with this approach.

As a side note, I will say that it seems like folks that use Apprise are used to just providing a complete URL and managing query params and such manually. However, from a UX standpoint, I prefer users not have to worry too much about syntactical details. I prefer Recyclarr have control over building the final URLs used to invoke the Apprise API.

**Comment by rcdailey** [comment]
Initial notification support has been implemented in commit 0707517bb8bf5f09df54b2e95ebfb7b0e7d8b78a and will be available in v7.3 (which isn't out yet). Documentation still needs to be updated, but will be completed prior to the release. I welcome feedback from folks that want to get an early preview on the edge builds.

**Comment by hvalev** [comment]
Great work @rcdailey. I would happily test out the preview version, just let me know how to get it.

**Comment by rcdailey** [comment]
Check the docker section on the wiki, it talks about edge builds there. You can also search "edge" on the wiki.

**Comment by hvalev** [comment]
Okay, I'm still a little unclear on how to configure the notifications. Let me know when you add that part to the documentation and I'll test it

**Comment by rcdailey** [comment]
> Okay, I'm still a little unclear on how to configure the notifications. Let me know when you add that part to the documentation and I'll test it

That's in the docs under the settings reference. Did you not find it?

**Comment by hvalev** [comment]
you mean [this one](https://recyclarr.dev/wiki/yaml/settings-reference/)?

**Comment by rcdailey** [comment]
I apologize, I just realized I never linked the documentation here 🤦‍♂️

These are the docs: https://next.recyclarr.dev/wiki/yaml/settings-reference/notifications/

**Comment by hvalev** [comment]
No worries and thanks :) I'll start testing

**Comment by hvalev** [comment]
I've set it up with an existing apprise instance in stateless mode with a discord webhook. It works in notifying that a sync was successful, but no information about what was synced was included. In the logs I get the following:
```
caafa177ed40:/$ recyclarr sync

===========================================
Processing Radarr Server: [movies]
===========================================

[INF] Skipped 39 Custom Formats that did not change
[INF] All custom formats are already up to date!
[INF] All quality profiles are up to date!
[INF] Using an explicit preferred ratio which will override values from the guide
[INF] All sizes for quality definition movie are already up to date!
[INF] Media naming is up to date!
[INF] Completed at 10/21/2024 15:56:38

===========================================
Processing Sonarr Server: [series]
===========================================

[INF] Skipped 34 Custom Formats that did not change
[INF] All custom formats are already up to date!
[INF] All quality profiles are up to date!
[INF] All sizes for quality definition series are already up to date!
[INF] Media naming is up to date!
[INF] Completed at 10/21/2024 15:56:41
```

however, the notification includes that the sync includes only the following
```
Recyclarr Sync Completed
---
```
Should the notifcation include the complete log as seen in the container? I'm running the `:edge` tag which I think should be the latest commit
