### ISSUE TITLE
unRAID stuck on "Starting cron schedule..."

### ISSUE THREAD

**Issue by chrisolson91** [recyclarr/recyclarr#116]
Hi there, 

I'm using the unRAID template and ran into an issue where when I run the container it starts fine but it get's stuck at "Starting cron schedule..." in the log file. I read in a different issue that you aren't the one that created the template so not sure if this is an issue with recyclarr itself or the template. Any thoughts on how to resolve this? Here is the full logs which isn't much...

time="2022-08-31T14:40:32-07:00" level=info msg="read crontab: /tmp/crontab"
Starting cron schedule...

**Comment by rcdailey** [comment]
What did you specify for `CRON_SCHEDULE`?

**Comment by Cjkeenan** [comment]
I have this problem as well and it is set to @daily. I assume it is a permission issue, but I am not sure how to change the permissions of cron.sh
```
/ $ ls -l
total 8
drwxr-xr-x    1 root     root            18 Aug 26 10:23 app
drwxr-xr-x    1 root     root           870 Aug 26 10:23 bin
drwxr-xr-x    1 99       users          272 Jul 25 10:58 config
-r-xr-xr-x    1 root     root           296 Aug 26 10:22 cron.sh
drwxr-xr-x    5 root     root           340 Aug 31 15:22 dev
-r-xr-xr-x    1 root     root           485 Aug 26 10:22 entrypoint.sh
drwxr-xr-x    1 root     root           566 Aug 31 15:22 etc
drwxr-xr-x    1 root     root             0 Aug  9 01:47 home
drwxr-xr-x    1 root     root           290 Aug  9 01:47 lib
drwxr-xr-x    1 root     root            28 Aug  9 01:47 media
drwxr-xr-x    1 root     root             0 Aug  9 01:47 mnt
drwxr-xr-x    1 root     root             0 Aug  9 01:47 opt
dr-xr-xr-x  499 root     root             0 Aug 31 15:22 proc
drwx------    1 root     root             0 Aug  9 01:47 root
drwxr-xr-x    1 root     root             0 Aug  9 01:47 run
drwxr-xr-x    1 root     root           800 Aug  9 01:47 sbin
drwxr-xr-x    1 root     root             0 Aug  9 01:47 srv
dr-xr-xr-x   13 root     root             0 Aug 31 15:22 sys
drwxrwxrwt    1 root     root            22 Aug 31 15:22 tmp
drwxr-xr-x    1 root     root            40 Aug  9 01:47 usr
drwxr-xr-x    1 root     root            86 Aug  9 01:47 var
```

**Comment by chrisolson91** [comment]
Yeah mine is set to @daily as well

**Comment by rcdailey** [comment]
If it's set to `@daily`, I have to ask the obvious question: Did you let this run for at least 2 days to see if it's really "stuck"? I do not expect any output after that log line until the cron job runs.

**Comment by rcdailey** [comment]
Yeah, give it some time. Let's see if it does something.

You can build your `recyclarr.yml` file manually if you want, or run `create-config` manually so it spits out the template in your volume mapping so you can edit it before the cron job runs. Sorry that the workflow for this isn't documented very well.

**Comment by chrisolson91** [comment]
Sound good. I'll give it a couple days and see how it goes. However, I did try and run "create-config" from the container console and it just returns the following. Am I missing something on how to run that command? 

/ $ create-config
sh: create-config: not found
/ $

**Comment by rcdailey** [comment]
Again I don't know the unraid way, but with vanilla docker compose I'd do:

```
docker-compose run --rm recyclarr create-config
```

I'll leave it up to you to find the Unraid-specific solution. I do not support that here, mostly because I have no experience with it. Sorry I can't be more helpful.

**Comment by chrisolson91** [comment]
Sounds good. I’ll see what I can come up with while i wait the 2 days. Is it expected that nothing is in the configuration directory after the container is installed?

**Comment by chrisolson91** [comment]
@rcdailey good call on waiting...patience is not my virtue lol. I just checked it and lots more in the logs now and all the files showed up in /config directory so I think we should be good. I just need to figure out how to run the docker-compose commands in unraid.

**Comment by rcdailey** [comment]
Glad it's working for you. I'll go ahead and close this issue. If you need further support, please use the Discussions tab at the top instead of opening an issue. Thanks!
