### ISSUE TITLE
Recyclarr download detected as potentially dangerous

### ISSUE THREAD

**Issue by Jeff254** [recyclarr/recyclarr#150]
After downloading Recyclarr using Google Chrome one gets a "Recyclarr is not commonly downloaded and may be dangerous" tag

![image](https://user-images.githubusercontent.com/31127234/206918167-2d677f2f-bd1a-40e4-beed-40bc97b25045.png)

**Comment by rcdailey** [comment]
I looked into this and I don't think there's anything I can reasonably do about it. The alert isn't particularly critical either. It's stating a fact that it isn't commonly downloaded and _may_ be dangerous. It's really just prompting you, as a user, to be aware of what you're doing. You understand that grabbing the release from Github is the correct place to get it, so the warning can be safely ignored.

If I find out later there's a way to do this that's reasonably easy and free, I will certainly do it.

I used [this](https://stackoverflow.com/questions/12231581/program-download-ie-chrome-is-not-commonly-downloaded-and-could-be-dangerou) as a resource, amongst a few other search results.
