### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x8007000E when used in a shared service

### ISSUE THREAD

**Issue by aqsd91** [recyclarr/recyclarr#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The program returns this error when trying to do anything
Failed to create CoreCLR, HRESULT: 0x8007000E

### Expected Behavior

Recyclarr starts and creates the config files and folders

### Steps To Reproduce

1. Using a shared service (Seedbox)
2. The config isnt created
3. Running 'recyclarr create-config'
4. Error : Failed to create CoreCLR, HRESULT: 0x8007000E

### Environment & Versions

```bash
- Operating System:Debian Linux
- Recyclarr Version: v4.0.0
- Sonarr Version:
- Radarr Version:
```

### Recyclarr Log File(s)

It didnt create any log file

### Configuration YAML

```YAML
There's no config file
```

**Comment by rcdailey** [comment]
Can you please read this github thread and see if it's the same issue?
https://github.com/dotnet/runtime/issues/13027

**Comment by aqsd91** [comment]
The last version that works is 2.6.1. And ulimit returns unlimited.

**Comment by rcdailey** [comment]
Please try running again with these 3 environment variables set:
https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing#how-do-i-debug-the-probing-properties-construction

I need to somehow get more diagnostic information to debug further. Between 2.6.1 and 3.0.0 was an upgrade to .NET 7. Not sure if that has something to do with it.

**Comment by aqsd91** [comment]
[trace.txt](https://github.com/recyclarr/recyclarr/files/10217171/trace.txt)
Here's the logfile.

**Comment by rcdailey** [comment]
Thank you for the logs! I'm going to open an issue over on the dotnet/runtime project for now. I do not believe this is something I can fix myself.

If you have the time, could you try out the adhoc build here?
https://github.com/recyclarr/recyclarr/actions/runs/3682346519

I'm working on a change that involves building Recyclarr on linux when publishing *to* linux platforms; which may (hopefully) fix this problem. Can you let me know what the results are?

Thanks again for all your help.

**Comment by rcdailey** [comment]
Also, what architecture are you running on? ARM / ARM64 / x64 / etc

Which build did you grab from the 4.0.0 release?

**Comment by aqsd91** [comment]
It's x86_64 GNU/Linux and i grabbed the linux-x64 release.

**Comment by rcdailey** [comment]
Can you run this command and attach the file? Use the correct path to recyclarr for your case.

strace -o stracelog.txt -f /path/to/your/app

**Comment by aqsd91** [comment]
It appears i'm not allowed to run that command sorry.

**Comment by rcdailey** [comment]
@aqsd91 can you respond to these questions from the dotnet devs?

---

It would be interesting to know how much memory the environment has and few other details like this. Here are some commands to get it:

```
cat /proc/meminfo
ulimit -a
```

I also wonder - is the user running it in some sort of container that could limit the memory for the process (like docker, etc)?

**Comment by aqsd91** [comment]
[cat.txt](https://github.com/recyclarr/recyclarr/files/10229360/cat.txt) [ulimit.txt](https://github.com/recyclarr/recyclarr/files/10229361/ulimit.txt) Here are the results of the commands. As for the second question i dont think so. I think its more of different VM's on a machine shared across users.

**Comment by rcdailey** [comment]
@aqsd91 Can you please read the response at [this comment](https://github.com/dotnet/runtime/issues/79612#issuecomment-1352378682) and let me know if that resolves the issue for you?

**Comment by aqsd91** [comment]
This doesn't resolve the issue, and the variable is correctly checked (via `echo ${DOTNET_GCHeapHardLimit}`)

**Comment by janvorli** [comment]
@aqsd91 can you please try setting the `DOTNET_GCHeapHardLimit` to even lower value? Maybe 7GB is still too much.
I would try to set it to `100000000`. Thank you.

**Comment by aqsd91** [comment]
It worked ! with 10000000

**Comment by janvorli** [comment]
Cool! Great to hear that.

**Comment by marquis-ng** [comment]
this should be a workaround, not a fix. Agree?

**Comment by rcdailey** [comment]
> @rcdailey I hope you are fine with me providing the ideas here on your github repo, I think it would be easier than ping-ponging back and forth between this thread and the one in dotnet runtime repo.

@janvorli I don't mind at all. In fact, thank you! I didn't mind doing the ping-pong; I just didn't want to inconvenience you too badly!

I'll respond to the other issue to discuss conclusions now that we have a workaround. Thanks again I really appreciate it!
