### ISSUE TITLE
Use CF names in output when removing a CF

### ISSUE THREAD

**Issue by yammes08** [recyclarr/recyclarr#159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the current version, when recyclarr removes a CF the output identifies it by the trash_id - i.e. a long JSON string. This is different to the output when a CF is added or updated, in which cases the name of the CF is used. The feature request is to use CF names when recyclarr removes a CF.

**Comment by rcdailey** [comment]
Fixed in v4.1.0
