### ISSUE TITLE
[WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.

### ISSUE THREAD

**Issue by bbccdd** [recyclarr/recyclarr#161]
Hi all, great work on improving recyclarr with version 3 and 4! One errro that keeps popping up and might be related to #153 is this. Should one add something in the docker-compose file?

# docker compose run --rm recyclarr sync
`
[WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
[...]
`

**Comment by rcdailey** [comment]
Remove `init: true` from your compose file.

**Comment by rcdailey** [comment]
Also I do not appreciate it when people skip the issue template. If you aren't willing to fill out the information, then use the discussion tab.

**Comment by bbccdd** [comment]
Solved indeed, thanks for the quick reply and for pointing to the issue templates.
