### ISSUE TITLE
Add date time to the log information

### ISSUE THREAD

**Issue by fabricionaweb** [recyclarr/recyclarr#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

**Setup:**

Docker image running manually with `recyclarr sync` throught unRaid

**Sceario:**

Im looking to the **docker logs** in unRaid interface, and I used to have trouble to figured out  when I had run, if the logs are the recent or not.

**Propose**

Add timestamp to the docker logs. 

The current logs is already amazing, and have been improve a lot, I really appreciate it. 

I just wonder if we could add a date/time at end of everything (or end of each section), maybe the runtime or something. This would help me to know exactly date/time it had run.

**Comment by rcdailey** [comment]
This is fixed in commit aaf810f
