### ISSUE TITLE
Add maximum and minimum quality values to config

### ISSUE THREAD

**Issue by 2fst4u** [recyclarr/recyclarr#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently you can add a ratio for preferred qualities, but it would be good if you could add either a ratio for min and max, or declare absolute values for these.

I would be fine with ratios applying to all my quality profiles but this may not work for others.

The preferred quality setting is almost pointless if you use custom formats because it seems to not do anything useful since it's the last thing Radarr/Sonarr uses to weight choices. If you're using custom formats these will take precedence over any preferred quality settings.

Setting a maximum setting would make it act in a more useful way. I set all my minimums to match trash guides but I manually bring down my maximums so I don't grab wildly oversized releases.

**Comment by rcdailey** [comment]
I am likely not going to make this change. It's simple enough right now to just not sync quality definitions with Recyclarr and instead manage the settings yourself directly in Radarr/Sonarr. Furthermore, the number of people that want to do this is very very small so it will be difficult to prioritize it.
