### ISSUE TITLE
Make `create config` use the Trash repo templates

### ISSUE THREAD

**Issue by rcdailey** [recyclarr/recyclarr#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Feature Description

As a user, I'd like the ability to create my default `recyclarr.yml` from a combination of the premade Recyclarr configuration files located in the official TRaSH repository here:

- [Sonarr](https://github.com/TRaSH-/Guides/tree/master/docs/Sonarr/recyclarr-config)
- [Radarr](https://github.com/TRaSH-/Guides/tree/master/docs/Radarr/recyclarr-config)

An example of the CLI experience for this might be:

```txt
# Without `--templates`, it would list your local configs instead
> recyclarr config list --templates

Sonarr:
- sonarr-web-1080p
- sonarr-web-4k

Radarr:
- radarr-remux-web-1080p
- radarr-remux-web-4k

> recyclarr config create -t sonarr-web-1080p -t radarr-remux-web-1080p
[INF] Created 'recyclarr.yml' from templates
```

The general flow the user would take:

1. Use the `config list --templates` command to list the available configuration templates for each service in the Trash repo.
2. Use `config create -t` to specify one or more template names to use to create a default `recyclarr.yml`.

## Implementation Notes

- When two or more templates are specified, those get concatenated together to form one final `recyclarr.yml` file.
- The existing `-c` option should allow the user to specify a custom location for the created file.
- TBD: Possibly issue an error/warning if the user tries to use templates from the same service?

## Trash Repo Changes

- Centralize all the templates under 1 parent directory (e.g. `docs/recyclarr/templates`)
- Create a new `templates.json` file at the root of that directory that describes the following for each template YAML file:
  - A display name to be used in the CLI when users run `config list --templates`
  - The relative path from the directory containing the `templates.json` file to the template YAML file.
  - A boolean flag that determines if this particular template should be rendered in the `config list --templates` output (mainly for SQP templates).
- Add a new entry to the `metadata.json` file at the root of the Trash repo which will include a path to the templates directory (in the previous example that would be `docs/recyclarr/templates`).

**Comment by yammes08** [comment]
This all looks good to me. I did remember that the main guide templates aren't actually detailed in the guide anywhere just yet, so these could be moved without issue. The SQP ones are linked via pins at the top of the relevant Discord channels, but again these could be changed.

I'll pick up both these points about relocating files with Trash though.

**Comment by yammes08** [comment]
@rcdailey - we can centralise the config files at `/docs/recyclarr-configs`. Would you want/need subfolders for Radarr/Sonarr, or just lump them all in one folder?

I can do a PR for the file relocations, I'll need some help with the json files though as I've no idea how to do these, haha!

**Comment by rcdailey** [comment]
The file structure under `/docs/recyclarr-configs` is up to you. The `templates.json` I mentioned in my OP states that the paths to each file will be under there, so you could put them wherever you want. As an example:

```txt
/docs/recyclarr-configs/
├── templates.json
├── config1.yml
├── config2.yml
├── more-configs/
│   └── config3.yml
└── other-configs/
    └── config4.yml
```

The `templates.json` would have:

```json
[
  {
    "template": "config1.yml",
    "display_name": "Config 1"
  },
  {
    "template": "config2.yml",
    "display_name": "Config 2"
  },
  {
    "template": "more-configs/config3.yml",
    "display_name": "Config 3"
  },
  {
    "template": "other-configs/config4.yml",
    "display_name": "Config 4"
  }
]
```

Since you offered to do the work, I'd also make sure to update the `metadata.json` too, as well as its schema, so that Recyclarr can find the `templates.json` file from the root of the repo. If you aren't comfortable with this change, I can open a PR for it later once I get closer to working on this. At that time, I'm also happy to do the `templates.json` too, if you want.

**Comment by yammes08** [comment]
So if I understand correctly, metadata.json would look a bit like this:

```json
{
  "$schema": "metadata.schema.json",
  "json_paths": {
    "radarr": {
      "custom_formats": ["docs/json/radarr/cf"],
      "qualities": ["docs/json/radarr/quality-size"],
      "naming": ["docs/json/radarr/naming"]
      "templates": ["docs/recyclarr-configs/radarr"]
    },
    "sonarr": {
      "release_profiles": ["docs/json/sonarr/rp"],
      "custom_formats": ["docs/json/sonarr/cf"],
      "qualities": ["docs/json/sonarr/quality-size"],
      "naming": ["docs/json/sonarr/naming"]
      "templates": ["docs/recyclarr-configs/sonarr"]
    }
  }
}

```
Then have 2x templates.json files - one under `docs/recyclarr-configs/radarr` and another under `docs/recyclarr-configs/sonarr`?

**Comment by rcdailey** [comment]
Nope, simpler than that:

`metadata.json`:

```json
{
  "$schema": "metadata.schema.json",
  "json_paths": {
    "radarr": {
      "custom_formats": ["docs/json/radarr/cf"],
      "qualities": ["docs/json/radarr/quality-size"],
      "naming": ["docs/json/radarr/naming"]
    },
    "sonarr": {
      "release_profiles": ["docs/json/sonarr/rp"],
      "custom_formats": ["docs/json/sonarr/cf"],
      "qualities": ["docs/json/sonarr/quality-size"],
      "naming": ["docs/json/sonarr/naming"]
    },
    "recyclarr": {
      "templates": "docs/recyclarr-configs"
    }
  }
}
```

`metadata.schema.json`:

```json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "$id": "https://raw.githubusercontent.com/TRaSH-/Guides/master/metadata.schema.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": { "type": "string" },
    "json_paths": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "radarr": { "$ref": "#/$defs/radarr" },
        "sonarr": { "$ref": "#/$defs/sonarr" },
        "recyclarr": { "$ref": "#/$defs/recyclarr" }
      }
    }
  },
  "$defs": {
    "paths_object": {
      "type": "array",
      "items": { "type": "string" }
    },
    "radarr": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "custom_formats": { "$ref": "#/$defs/paths_object" },
        "qualities": { "$ref": "#/$defs/paths_object" },
        "naming": { "$ref": "#/$defs/paths_object" }
      }
    },
    "sonarr": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "custom_formats": { "$ref": "#/$defs/paths_object" },
        "release_profiles": { "$ref": "#/$defs/paths_object" },
        "qualities": { "$ref": "#/$defs/paths_object" },
        "naming": { "$ref": "#/$defs/paths_object" }
      }
    },
    "recyclarr": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "templates": { "type": "string" }
      }
    }
  }
}
```
```

**Comment by rcdailey** [comment]
> Then have 2x templates.json files - one under docs/recyclarr-configs/radarr and another under docs/recyclarr-configs/sonarr?

No to this as well. You'll follow [my previous post](https://github.com/recyclarr/recyclarr/issues/171#issuecomment-1426900358) for this. No need for two template json files.
