### ISSUE TITLE
Indexer configs

### ISSUE THREAD

**Issue by sgtsquiggs** [recyclarr/recyclarr#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I'm using Jackett and I utilize a lot of different indexers. It would be really sick if I could use recyclarr to configure radarr/sonarr instead of having to manually add each jackett indexer for each radarr/sonarr instance.

**Comment by rcdailey** [comment]
Have a look at [Prowlarr](https://github.com/Prowlarr/Prowlarr). It does a good enough job of indexer syncing that I won't be doing it in Recyclarr.

**Comment by sgtsquiggs** [comment]
Hah! Hadn't heard of that one. Looks like exactly what I wanted.
