### ISSUE TITLE
Radarr and Sonarr Naming Scheme Sync

### ISSUE THREAD

**Issue by benniblot** [recyclarr/recyclarr#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It would be cool if Recyclarr would be able to sync the naming scheme for Sonarr (tv and anime respectively) and Radarr

Trash Guide has a recommended naming  scheme that defines how Sonarr and Radarr renames content (set in the media management settings tab of Radarr and Sonarr):
 https://trash-guides.info/Radarr/Radarr-recommended-naming-scheme/
https://trash-guides.info/Sonarr/Sonarr-recommended-naming-scheme/

**Comment by rcdailey** [comment]
Your request is unclear. Can you edit your post with more detail? Examples help as well.

**Comment by benniblot** [comment]
sorry about that, updated it

**Comment by rcdailey** [comment]
That helps, thank you. Good news is that this is already on my roadmap to be done soon :)
