### ISSUE TITLE
v5.3.1 WIN x64 executable issue

### ISSUE THREAD

**Issue by Fishairman90** [recyclarr/recyclarr#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Just downloaded the latest [v5.3.1] on a Win x65 machine. Executable opens a command prompt for a fraction of a second and then closes. Tried running as Admin and same issue. 

### Expected Behavior

Should run/download files in parent folder. 

### Steps To Reproduce

Download the latest version. 

### Environment & Versions

```bash
- Operating System: Win 11 Pro
- Architecture: x64 bit
- Recyclarr Version: v5.3.1
- Recyclarr Build: v5.3.1
- Sonarr Version: N/A
- Radarr Version: N/A
```

### Recyclarr Log File(s)

Don't have any

### Configuration YAML

```YAML
Don't have any
```

### Sonarr / Radarr Logs

N/A

**Comment by rcdailey** [comment]
It's clear to me that very little effort was put into completing the issue report template. Furthermore, this is more of a support request which belongs in the Discussions tab.
