### ISSUE TITLE
Recyclarr 5.4.0 appears to ignore includeCustomFormatWhenRenaming on CFs

### ISSUE THREAD

**Issue by datcactus** [recyclarr/recyclarr#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When syncing a CF with `includeCustomFormatWhenRenaming: true` recyclarr does not honor the setting. They all sync as `false` which will cause renaming and scoring issues as this mainly applies to streaming service CFs.

### Expected Behavior

Sync should honor `includeCustomFormatWhenRenaming` setting as it did on 5.3.1.

### Steps To Reproduce

1. Use any CF with `includeCustomFormatWhenRenaming: true` on 5.3.1
2. Sync the CF
3. Note that the setting is enabled in the CF
4. Upgrade to 5.4.0
5. Sync the CF
6. Note that the setting is now disabled in the CF

### Environment & Versions

```bash
- Operating System: Ubuntu 22.04
- Architecture: x64
- Recyclarr Version: 5.4.0
- Recyclarr Build: linux/amd64
- Sonarr Version: 4.0.0.646
- Radarr Version: 4.7.5.7809
```

### Recyclarr Log File(s)

Verbose since debug doesn't show the config piece changing https://gist.github.com/datcactus/b43040776527c7d95f964ba8f4ea4cc6

### Configuration YAML

https://gist.github.com/datcactus/5af31a57739905669affa7d1629dadb3

**Comment by rcdailey** [comment]
Fixed in v5.4.1
