### ISSUE TITLE
Add support for creating a new yaml template from existing configuration in Radarr/Sonarr

### ISSUE THREAD

**Issue by mycarrysun** [recyclarr/recyclarr#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Given that some users may prefer to use the UI in Radarr/Sonarr to update their config initially (or especially if they had a lot of customizations before installing/finding out about recyclarr), it would be nice to be able to pull all of that config into a recyclarr template yaml file.

I don't see any issues previously about this kind of feature but would this be desirable to folks?

**Comment by mycarrysun** [comment]
Looking around more, would this be more of a use case for Notifiarr?

**Comment by rcdailey** [comment]
So you're suggesting an export utility for Sonarr/Radarr, that is capable of converting existing settings to a Recyclarr-compatible YAML file?

Not only is that a ton of work, but I also don't think it aligns very well with what I'm interested in accomplishing with my project (and more importantly, my time). I have a ton of other things I have plans for and unfortunately I don't see myself ever getting around to something like this.

Thank you for taking the time to share your idea!
