### ISSUE TITLE
`recyclarr list` Incorrectly Parsing `Season Pack (New "Release Type" Handling, Sonarr v4.0.2.1262+ only)` From Guides

### ISSUE THREAD

**Issue by owine** [recyclarr/recyclarr#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`recyclarr list custom-formats sonarr`
```
...
          - ae58039e1319178e6be73caab5c42166 # SHO
          -  # Season Pack
          - 3bc5f395426614e155e585a2f056cdf1 # Season Pack
...
```

The `Season Pack (New "Release Type" Handling, Sonarr v4.0.2.1262+ only)` CF is Guides Only (no `trash_id`) but is improperly parsed (I presume the special characters causes this) resulting in the `-  # Season Pack` list entry.

### Expected Behavior

`recyclarr list custom-formats sonarr`
```
...
          - ae58039e1319178e6be73caab5c42166 # SHO
          - 3bc5f395426614e155e585a2f056cdf1 # Season Pack
...
```

The `Season Pack (New "Release Type" Handling, Sonarr v4.0.2.1262+ only)` CF is skipped in the list.

### Steps To Reproduce

`recyclarr list custom-formats sonarr`

### Environment & Versions

```bash
- Operating System: Ubuntu 22.04
- Architecture: x64
- Recyclarr Version: 6.0.1
- Recyclarr Build: linux-x64
- Sonarr Version: 4.0.2.1183
- Radarr Version: 5.3.6.8612
```

### Recyclarr Log File(s)

n/a

### Configuration YAML

```YAML
n/a
```

**Comment by rcdailey** [comment]
Excellent report. Thank you for this. This will be fixed in the next release!
