### ISSUE TITLE
Error on sync Trash Guides Repo: Exception

### ISSUE THREAD

**Issue by simyery** [recyclarr/recyclarr#239]
Hi

I appear to be getting this error when recyclarr runs

Trash Guides Repo: Exception while parsing settings.yml at line 18: Property 'sonarr' not found on type 'Recyclarr.Settings.SettingsValues'.

Not sure what could be causing this now as i had it running fine a few days ago
The only thing i have change would be adding more trash ids under quality_profiles on my radarr section loter in the doc

Screen shot bellow of settings.yml at line 18
![Screenshot 2024-04-28 220048](https://github.com/recyclarr/recyclarr/assets/11280617/af954630-e24b-479c-9344-8a90dc9bafa1)

**Comment by rcdailey** [comment]
Closed due to not following the issue report template. Issues are not the place to open discussions.
