### ISSUE TITLE
[Request] enabling "guide-only" as available trash id in recyclarr.yml conf

### ISSUE THREAD

**Issue by salvo-github** [recyclarr/recyclarr#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello,

i've opened a similar request in Trash-guide (https://github.com/TRaSH-Guides/Guides/issues/2084) to ask to create the same CF but with a configuration file that recyclarr can understand.

Having said that, what about enabling recycler to understand a file path (eg docs/json/guide-only/language-not-original.json) or a full configuration instead of the trash id? 

I would propose a PR myself but I don't know C#

**Comment by salvo-github** [comment]
i've ended up using a forked trash guide repo. This request can be closed because i've seen other issues asking about custom cf definition in yml file

**Comment by rcdailey** [comment]
Be sure to upvote #218 if you would find that important!
