### ISSUE TITLE
Notification Toggles for Errors/Changes Only

### ISSUE THREAD

**Issue by owine** [recyclarr/recyclarr#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Requesting a couple of toggles for notifications to filter down the notifications sent:

- Errors Only - this would only send a notification if a sync had errors
- Changes Only - this would only send a notification if a sync made changes
- Changes or Errors Only - this would only send a notification if the sync made changes or encountered errors

To me, a notification on every sync is unnecessary noise and the ability to filter out syncs that change nothing would be helpful.

**Comment by rcdailey** [comment]
Here's a version that I'm thinking of implementing:

```yml
notifications:
  verbosity: normal # This is new
  apprise:
    # Your apprise settings here
```

This would allow you to configure the verbosity of notifications using a set of fixed verbosity levels, such as:

- `normal`: Includes errors, warnings, informational (changes). This would be the default.
- `detailed`: Everything in normal, plus empty messages (no changes)
- `minimal`: Only errors and warnings

Open to feedback.
