### ISSUE TITLE
Improved Logging of Warnings in Certain Situations

### ISSUE THREAD

**Issue by owine** [recyclarr/recyclarr#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A couple of instances that I have noticed that standard logging/print to screen does not show an error/warning that I would expect and would be helpful for troubleshooting.

- Error updating Git repository (in my instance it was an auth error) leading the user to believe Recyclarr is deploying from the latest commit on the repo but may be deploying from the last commit checked out by the local cache. I would expect to be warned that the update failed.
~~- Including a Quality in a Quality Profile that does not have qualtity definitions on the guide. I noticed this with `Bluray-576p` not being added to my Profile until https://github.com/TRaSH-Guides/Guides/commit/1eb8245fc3024a092e86d042592084b280ea113e. I would expect Recyclarr to notify me there is a listed Quality it cannot handle as the user would expect.~~

**Comment by rcdailey** [comment]
For the first point, I need an example of what kind of auth error you're talking about. Since the clone URLs use `https`, access is allowed without authenticating.

For the second point, could you please provide a YAML config I can copy and paste for testing purposes?

**Comment by owine** [comment]
Second issue relating to Quality Profiles appears to be invalid. I cannot reproduce it again.

**Comment by rcdailey** [comment]
Thanks for the update owine. I'll go ahead and close this as resolved. If that second issue ever pops up again in the future, please open another bug report and I'm happy to jump on it!
