### ISSUE TITLE
Docker: git commands fail because of a permission issue

### ISSUE THREAD

**Issue by timothe** [recyclarr/recyclarr#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use the latest Docker image on MacOS. The behaviour has been observed on Synology too.
I used the default parameters and us a bound volume for config files.
However, `recyclarr config create`, `recyclarr sync` and the cron task all fail because of a similar issue linked to git.
Example:
```
~ $ recyclarr sync
                              
[ERR] Non-zero exit code 128 while executing Git command: fatal: detected dubious ownership in repository at '/config/repositories/trash-guides'
To add an exception for this directory, call:
        git config --global --add safe.directory /config/repositories/trash-guides
~ $ git config --global --add safe.directory /config/repositories/trash-guides
error: could not lock config file //.gitconfig: Permission denied
```
I can't create a `.gitconfig` file, `sudo` can't work, I can't find any lock file, I checked the permissions:
```
/config $ ls -al
total 16
drwxr-xr-x    9 root     root           288 Nov 19 09:02 .
drwxr-xr-x    1 root     root          4096 Nov 19 09:06 ..
-rw-r--r--    1 1000     1000          6148 Nov 19 08:59 .DS_Store
drwxr-xr-x    2 1000     1000            64 Nov 18 19:26 cache
drwxr-xr-x    2 1000     1000            64 Nov 18 19:26 configs
drwxr-xr-x    2 1000     1000            64 Nov 18 19:26 includes
drwxr-xr-x    3 1000     1000            96 Nov 18 19:26 logs
drwxr-xr-x    4 1000     1000           128 Nov 19 09:07 repositories
-rw-r--r--    1 1000     1000           327 Nov 18 19:26 settings.yml
```
The guides and templates are not imported, however the folders and files are created.
Recyclarr can't start to work as it can't communicate with the repo.

### Expected Behavior

Guides would be imported and synced

### Steps To Reproduce

1. Run the command:
```
docker run -d \
  --name=recyclarr \
  --user 1000:1000 \
  -e TZ=Europe/London \
  -v /my/own/directory:/config \
  --restart unless-stopped \
  ghcr.io/recyclarr/recyclarr:latest
```

2. Run the command:
`docker exec recyclarr recyclarr config create`
(or use Docker Desktop)

### Environment & Versions

```bash
- Operating System:macOS Sequoia, DSM 7.2.2
- Architecture: ARM, x86
- Recyclarr Version: latest (7.4.0)
- Recyclarr Build: Docker
- Sonarr Version: n/a
- Radarr Version: n/a
```

### Recyclarr Log File(s)

[recyclarr_2024-11-19_09-24-57.debug.log](https://github.com/user-attachments/files/17812753/recyclarr_2024-11-19_09-24-57.debug.log)

### Configuration YAML

```YAML
n/a
```

### Sonarr / Radarr Logs

n/a

**Comment by Piwero** [comment]
> I might have solved the issue... Creating the container using another user than 1000:1000 doesn't work. It still applies those IDs. Instead, I used the PID and GID of my host machine user, and I don't get the error anymore. Here's the result:
> 
> ```
> ~ $ recyclarr sync
> 
> ===========================================
> Processing Radarr Server: [hd-bluray-web]
> ===========================================
> 
> [INF] Created 32 New Custom Formats
> [INF] Total of 32 custom formats were synced
> [INF] Created 1 Profiles: ["HD Bluray + WEB"]
> [INF] A total of 1 profiles were synced. 1 contain quality changes and 1 contain updated scores
> [INF] Total of 14 sizes were synced for quality definition movie
> [INF] Completed at 11/19/2024 10:54:08
> ```
> 
> Still posting this for posterity :)

@timothe good you found the solution, but how did you get the PID and GID and what did you change after it?
I'm trying with kubernetes, so I can't run docker top. Thanks

**Comment by timothe** [comment]
So I used a docker compose as below:
```
services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: xxxx:xxx
    network_mode: host
    volumes:
      - /volume1/media/config/recyclarr:/config
    environment:
      - TZ=Europe/London
      - RECYCLARR_CREATE_CONFIG=true
```

There xxxx:xxx are uid:gid of my current user (owner of the folder). I'm on a Synology NAS - under Linux, so I used the `id` command.
