### ISSUE TITLE
Include changed items in notifications and logs

### ISSUE THREAD

**Issue by pikeas** [recyclarr/recyclarr#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Notification:
```
### instance `radarr`

Information:

- Custom Formats Synced: 1
```

Server log:
```
[INF] Updated 1 Existing Custom Formats
[INF] Skipped 142 Custom Formats that did not change
[INF] Total of 1 custom formats were synced
```

There's no easy way to tell what actually changed - please log the details (at least name and score) for each changed CF.

**Comment by rcdailey** [comment]
Notifications aren't intended to provide that level of detail. Review the log files for more specifics.

**Comment by pikeas** [comment]
> Review the log files for more specifics

I included a log snippet above, it doesn't output which CFs changed.

**Comment by rcdailey** [comment]
> > Review the log files for more specifics
> 
> I included a log snippet above, it doesn't output which CFs changed.

You are looking at console logs, not file logs. The information you want is logged with debug severity, which is only available in the file logs by default. If you also want them in the console logs, you need to run with the `--debug` option.
