### ISSUE TITLE
Automatic Updates of Native Installs

### ISSUE THREAD

**Issue by eatnumber1** [recyclarr/recyclarr#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hi there,

I was looking to install recyclarr natively. I don't generally use Docker (although I've got nothing against it, it's just more config to deal with), however it looks like if I natively install recyclarr it doesn't auto-update, whereas Docker will.

So as a feature request, can you add auto-updating support to native installs?

However, I came up with an alternative. Kind of a half-way between native and using Docker Compose. Under this setup, Docker (without compose) is used, but it's hidden behind a script, and I also wrote native systemd unit files so it "feels" native, even though Docker is used under the hood. Here's the setup:

Add a `recyclarr` user, with its home directory in /var/lib/recyclarr. That's where recyclarr's config directory will be.

```bash
useradd -d /var/lib/recyclarr -r -s /usr/sbin/nologin -m recyclarr
```

Create /usr/local/bin/recyclarr

```bash
#!/bin/bash
set -e

readonly IMAGE="ghcr.io/recyclarr/recyclarr"

declare -a flags
flags+=( --rm )
flags+=( --user $(id -u recyclarr):$(id -g recyclarr) )
flags+=( --volume ~recyclarr:/config )
flags+=( --env "TZ=America/Los Angeles" )
flags+=( --network host )

if [[ -t 1 ]]; then
  flags+=( --tty )
fi

exec /usr/bin/docker run "${flags[@]}" "$IMAGE" "$@"
```

Create /etc/systemd/system/recyclarr.service

```ini
[Unit]
Description=Update sonarr and radarr profiles using recyclarr
Wants=network-online.target
After=syslog.target network-online.target sonarr.service radarr.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/recyclarr sync
```

Create /etc/systemd/system/recyclarr.timer

```ini
[Unit]
Description=Update sonarr and radarr profiles using recyclarr

[Timer]
OnCalendar=daily
RandomizedDelaySec=12h
Persistent=true

[Install]
WantedBy=timers.target
```

Then enable it

```
systemctl enable recyclarr.timer
```

With this, recyclarr syncs daily, and I can use it on my machine natively by running the `recyclarr` command (as root). It's possible to make this work without first being root too (e.g. https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo), but I don't care so didn't set that up.

**Comment by rcdailey** [comment]
In my opinion, auto updates, delivery, and installation are package manager concerns. There's several package managers out there you could choose to contribute to. This would make Recyclarr and its updates available to you and many others.

However, I will not be implementing any auto-update functionality directly into Recyclarr. There's a lot of reasons for this, but the simplest is that it's out of scope for my project.
