### ISSUE TITLE
New Recyclarr not syncing past the first term

### ISSUE THREAD

**Issue by Guegs** [recyclarr/recyclarr#69]
Version 2.0.1

I updated to the new Recyclarr release and was noticing some strange releases getting downloaded that didn't seem consistent with what I was getting before the upgrade. It appears that Recyclarr is not syncing releases past the first 'term' in the [streaming.json](https://github.com/TRaSH-/Guides/blob/master/docs/json/sonarr/streaming.json) (I haven't checked any profiles past this).

Pictures to more clearly demonstrate what I am talking about:

Streaming.json from github. Bordered in red is the 'term' that is not syncing to Sonarr. 
![image](https://user-images.githubusercontent.com/5591398/169584523-cb7495e2-a6a0-475e-b781-715c1e4e9744.png)

My Recyclarr.yaml showing which trash_ids I have configured. 
![image](https://user-images.githubusercontent.com/5591398/169584416-050d457f-218b-4299-b487-fccde2e0f1a6.png)

Sonarr release profile for streaming services.
![image](https://user-images.githubusercontent.com/5591398/169584239-a9b2f438-25f4-4aed-aa50-ab5836458c30.png)

**Comment by rcdailey** [comment]
Can you check if it still does this if you remove `filter:` and all properties under it? I am curious if the filtering logic is causing this. Thanks in advance if you can test.

**Comment by Guegs** [comment]
Can confirm that the issue is resolved if I remove `filter:` and the properties under it. 
![image](https://user-images.githubusercontent.com/5591398/169595755-fc503d11-f183-4895-9221-0169a4b5404c.png)
![image](https://user-images.githubusercontent.com/5591398/169595794-7115d51d-3c09-4bb0-9f7f-3bdc050e7265.png)

**Comment by rcdailey** [comment]
Thanks for testing. I imagine this will be a simple fix and just an oversight on my part. I'll try to get to this today or tomorrow.

**Comment by rcdailey** [comment]
Fixed in v2.0.2. Thanks for the bug report!
