### ISSUE TITLE
[REQ] Add the possibility to run recyclarr in docker.

### ISSUE THREAD

**Issue by nmbrg** [recyclarr/recyclarr#70]
Would be nice to have the possibility to run it in a docker container with automatic checks in a configurable timeframe.

can only talk for myself, but i do not want to run it on a client pc and have no need for a VM other than recyclarr.

**Comment by rcdailey** [comment]
This is already in progress See #45 and #51 .

**Comment by rcdailey** [comment]
Docker image is officially available at the link below.

https://github.com/recyclarr/recyclarr/pkgs/container/recyclarr
