### ISSUE TITLE
Recyclarr does not remove custom formats when configured to do so

### ISSUE THREAD

**Issue by klepp0906** [recyclarr/recyclarr#71]
I've been experimenting around with some of the changes and decided to enable `delete_old_custom_formats: true` so i could add and remove custom formats from radarr by simply commenting them out. 

it doesnt seem to work at current.

**Comment by skayo** [comment]
would it be possible for you to provide some logs (command output) or screenshots (before/after) or anything further that could help?

**Comment by klepp0906** [comment]
yea i just put this up real quick as voidpointer in discord asked me to.  i assumed it was to function as a reminder.  someone else noted there it wasnt working as well.  actually came across it while working on something else but mentioned it in passing.

as far as i can recall the cmd output shows nothing abnormal the formats just do not remove from radarr when running a recyclarr radarr and having it configured to do so in the yml.

all that being said, if you want screenshots or whatnot of something specific i'll be glad to.

**Comment by skayo** [comment]
Oh I didn't know you've talked on Discord, then it's alright I guess

**Comment by klepp0906** [comment]
sure, let me give it a quick edit to clear out the essentials.  im actually working on it as we speak.  trying to expand upon it to make it as useable and viable long term as i can so i apologize for much of the mess.  ignore the comment-haven :P 

EDIT: here ya go.
[recyclarr.txt](https://github.com/recyclarr/recyclarr/files/8763785/recyclarr.txt)

apparently cant upload yml here so have to change the extension back for highlighting/formatting i assume.
