### ISSUE TITLE
Docker changes config location upon run.

### ISSUE THREAD

**Issue by JonzaUK** [recyclarr/recyclarr#79]
Upon running recyclarr (docker) for the first time, recyclarr will look for the config at /config/recyclarr.yml - once recyclarr.yml is placed and a run is executed it will fetch the guide data but then look for the config at /config/.config/recyclarr/recyclarr.yml

LOGS:

https://gist.github.com/JonzaUK/62a719438a59195fa9a190d3a3c1cf39 (First Run)

https://gist.github.com/JonzaUK/00e5b29a4504b1386be0361eff8104fa (Run after placing config (recyclarr.yml)

**Comment by JonzaUK** [comment]
When running `recyclarr sonarr --app-data /config` recyclarr runs fine. but all data from is /config/.config/recyclarr, now appears in the main /config folder.

LOGS for run using `recyclarr sonarr --app-data /config` 
https://gist.github.com/JonzaUK/4072679a0ff8b3618f069b0a7b99ac80

**Comment by JonzaUK** [comment]
`/config`
<img width="626" alt="image" src="https://user-images.githubusercontent.com/21015102/171743768-9058abb9-1c78-451c-a912-b8f0c0c0f6e2.png">
`/config/.config/recyclarr`
<img width="562" alt="image" src="https://user-images.githubusercontent.com/21015102/171743793-acc90973-000a-4f03-8175-02ec4592c22c.png">

**Comment by rcdailey** [comment]
Can someone confirm if v2.2 fixes this?

**Comment by rcdailey** [comment]
> Mine works perfectly, now If I define the --appdata upon running via the terminal.

Can you try without it? It should work without it in the latest version.

**Comment by JonzaUK** [comment]
> 

Yep works as intended running "recyclarr sonarr"

**Comment by rcdailey** [comment]
Awesome, thank you for confirming. I'll close this issue, then.
