### ISSUE TITLE
unRAID Docker Image - Failure processing application bundle.

### ISSUE THREAD

**Issue by skayo** [recyclarr/recyclarr#86]
### Discussed in https://github.com/recyclarr/recyclarr/discussions/85

<div type='discussions-op-text'>

<sup>Originally posted by **KRiSX85** June  8, 2022</sup>
Hi, so I noticed the new docker image in the unRAID apps listing and decided to give it a try. I found that running it would immediately stop and produce an error in the logs. I went ahead and put a config file in /appdata/recyclarr that I generated elsewhere and the docker container will start and stay running now. However every day I'm now seeing the following...

```
-------------------------------------------------------------
 Executing Cron Tasks: Wed Jun  8 00:00:00 AEST 2022
-------------------------------------------------------------

Failure processing application bundle.
Failed to create directory [/tmp/.net/recyclarr/] for extracting bundled files.
```

If I enter the Console for the container and run either the cron.sh script itself or the individual commands, it all works perfectly, so I'm not sure why its producing these errors and would really appreciate assistance with it.

Thanks</div>

**Comment by skayo** [comment]
@KRiSX85, please note that the unRAID template is not provided by us and issues like this might not have anything to do with Recyclarr. Although, this sounds like a problem with file permissions.

Here is the unRAID template: https://github.com/tritones/unraid-templates/blob/main/templates/recyclarr.xml

**Comment by rcdailey** [comment]
@KRiSX85: Please show me your `docker-compose.yml` so I can attempt to reproduce this. Or whatever the unraid equivalent is.

**Comment by KRiSX85** [comment]
> @KRiSX85, please note that the unRAID template is not provided by us and issues like this might not have anything to do with Recyclarr. Although, this sounds like a problem with file permissions.
> 
> Here is the unRAID template: https://github.com/tritones/unraid-templates/blob/main/templates/recyclarr.xml

thanks for the reply, exactly right, I had to modify the permissions on the recyclarr folder under appdata, unfortunately it either got messed up somehow or the docker app doesn't set it up properly and yes sorry to post here when I know it isn't maintained by you, but this is where the support links sent me - either way thanks and hopefully this will help anyone else that may run into the issue, I simply matched permissions on the folder to the rest of my containers and its all good now
